import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Header} from "@/shared/ui/header";
import {BottomNav} from "@/feature/bottom-nav";
import {useRouter, useSearchParams} from "next/navigation";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

enum Menu {
    MARKET = "/",
    TOP = "top",
    ROCKET = "rocket",
    FRIENDS = "friends",
    PROFILE = "profile",
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    const router = useRouter();
    const searchParams = useSearchParams();

    (() => {
        const startParams = searchParams.get("startapp");

        if (startParams) {
            switch (startParams) {
                case Menu.MARKET:
                    router.push(Menu.MARKET);
                    break;
                case Menu.TOP:
                    router.push(Menu.TOP);
                    break;
                case Menu.ROCKET:
                    router.push(Menu.ROCKET);
                    break;
                case Menu.FRIENDS:
                    router.push(Menu.FRIENDS);
                    break;
                case Menu.PROFILE:
                    router.push(Menu.PROFILE);
                    break;
                default:
                    return
            }
        }
    })()

    const imageUrls: string[] = [
        '/tonCoin.svg',
        '/file.svg',
        '/globe.svg',
        '/logo.svg',
        '/next.svg',
        '/nft-1.png',
        '/tonCoin.svg',
        '/tonkeeper.svg',
        '/vercel.svg',
        '/window.svg',
        '/bottomNav/friends.svg',
        '/bottomNav/market.svg',
        '/bottomNav/profile.svg',
        '/bottomNav/rocket.svg',
        '/bottomNav/top.svg',
        '/friends/nftGoLogo.png',
        '/friends/ticket.png',
        '/profile/lock.svg',
        '/profile/nft-2.svg',
        '/profile/nftGoLogo.svg',
        '/rocket/deposit-2.svg',
        '/rocket/rocket.png',
        '/rocket/wifi.png'
    ];


    return (
        <html lang="en">
        <head>
            {imageUrls.map((url, index) => (
                <link key={index} rel="preload" href={url} as="image"/>
            ))}
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#150f27]`}
        >
        <Header/>
        <div className={'bg-[#150f27] min-h-screen text-white px-[15px] mx-auto relative'}>
            {children}
        </div>
        <BottomNav/>
        </body>
        </html>
    );
}
